/* 
 * FDB Prizm Services
 *
 * Web API for accessing medical device information
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace DeviceSample.Model
{
    /// <summary>
    /// AlternateDeviceNameInfo
    /// </summary>
    [DataContract]
    public partial class AlternateDeviceNameInfo :  IEquatable<AlternateDeviceNameInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AlternateDeviceNameInfo" /> class.
        /// </summary>
        /// <param name="AlternateDeviceName">AlternateDeviceName.</param>
        public AlternateDeviceNameInfo(string AlternateDeviceName = default(string))
        {
            this.AlternateDeviceName = AlternateDeviceName;
        }
        
        /// <summary>
        /// Gets or Sets AlternateDeviceName
        /// </summary>
        [DataMember(Name="AlternateDeviceName", EmitDefaultValue=false)]
        public string AlternateDeviceName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AlternateDeviceNameInfo {\n");
            sb.Append("  AlternateDeviceName: ").Append(AlternateDeviceName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as AlternateDeviceNameInfo);
        }

        /// <summary>
        /// Returns true if AlternateDeviceNameInfo instances are equal
        /// </summary>
        /// <param name="other">Instance of AlternateDeviceNameInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AlternateDeviceNameInfo other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AlternateDeviceName == other.AlternateDeviceName ||
                    this.AlternateDeviceName != null &&
                    this.AlternateDeviceName.Equals(other.AlternateDeviceName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AlternateDeviceName != null)
                    hash = hash * 59 + this.AlternateDeviceName.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
