/* 
 * FDB Prizm Services
 *
 * Web API for accessing medical device information
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace DeviceSample.Model
{
    /// <summary>
    /// CompanyAlias
    /// </summary>
    [DataContract]
    public partial class CompanyAlias :  IEquatable<CompanyAlias>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompanyAlias" /> class.
        /// </summary>
        /// <param name="CompanyAliasName">CompanyAliasName.</param>
        public CompanyAlias(string CompanyAliasName = default(string))
        {
            this.CompanyAliasName = CompanyAliasName;
        }
        
        /// <summary>
        /// Gets or Sets CompanyAliasName
        /// </summary>
        [DataMember(Name="CompanyAliasName", EmitDefaultValue=false)]
        public string CompanyAliasName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CompanyAlias {\n");
            sb.Append("  CompanyAliasName: ").Append(CompanyAliasName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CompanyAlias);
        }

        /// <summary>
        /// Returns true if CompanyAlias instances are equal
        /// </summary>
        /// <param name="other">Instance of CompanyAlias to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CompanyAlias other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.CompanyAliasName == other.CompanyAliasName ||
                    this.CompanyAliasName != null &&
                    this.CompanyAliasName.Equals(other.CompanyAliasName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.CompanyAliasName != null)
                    hash = hash * 59 + this.CompanyAliasName.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
