/* 
 * FDB Device Services
 *
 * Web API for accessing medical device information
 *
 * OpenAPI spec version: 1.01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace DeviceSample.Model
{
    /// <summary>
    /// Returns the device identifiers from various sources
    /// </summary>
    [DataContract]
    public partial class DeviceIdentifier :  IEquatable<DeviceIdentifier>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceIdentifier" /> class.
        /// </summary>
        /// <param name="ExternalDeviceId">Returns the external identifier.</param>
        /// <param name="ExternalDeviceType">Returns the type of the external identifier. Examples - GTIN, HIBC, UPC, ISBT 128, UPN, NHRIC, NDC-NHRIC, NDC, PIN.</param>
        /// <param name="ExternalDeviceAgency">Returns the agency the identifier is from. Examples - FDA, GS1, HIBCC, ICCBBA, Manufacturer, NCPDP.</param>
        /// <param name="ExternalDeviceDesignator">Returns the designator of the device identifier. Examples - Primary, Secondary, Unspecified, Direct Marketing, Package, Unit Of Use.</param>
        public DeviceIdentifier(string ExternalDeviceId = null, string ExternalDeviceType = null, string ExternalDeviceAgency = null, string ExternalDeviceDesignator = null)
        {
            this.ExternalDeviceId = ExternalDeviceId;
            this.ExternalDeviceType = ExternalDeviceType;
            this.ExternalDeviceAgency = ExternalDeviceAgency;
            this.ExternalDeviceDesignator = ExternalDeviceDesignator;
        }
        
        /// <summary>
        /// Returns the external identifier
        /// </summary>
        /// <value>Returns the external identifier</value>
        [DataMember(Name="ExternalDeviceId", EmitDefaultValue=false)]
        public string ExternalDeviceId { get; set; }
        /// <summary>
        /// Returns the type of the external identifier. Examples - GTIN, HIBC, UPC, ISBT 128, UPN, NHRIC, NDC-NHRIC, NDC, PIN
        /// </summary>
        /// <value>Returns the type of the external identifier. Examples - GTIN, HIBC, UPC, ISBT 128, UPN, NHRIC, NDC-NHRIC, NDC, PIN</value>
        [DataMember(Name="ExternalDeviceType", EmitDefaultValue=false)]
        public string ExternalDeviceType { get; set; }
        /// <summary>
        /// Returns the agency the identifier is from. Examples - FDA, GS1, HIBCC, ICCBBA, Manufacturer, NCPDP
        /// </summary>
        /// <value>Returns the agency the identifier is from. Examples - FDA, GS1, HIBCC, ICCBBA, Manufacturer, NCPDP</value>
        [DataMember(Name="ExternalDeviceAgency", EmitDefaultValue=false)]
        public string ExternalDeviceAgency { get; set; }
        /// <summary>
        /// Returns the designator of the device identifier. Examples - Primary, Secondary, Unspecified, Direct Marketing, Package, Unit Of Use
        /// </summary>
        /// <value>Returns the designator of the device identifier. Examples - Primary, Secondary, Unspecified, Direct Marketing, Package, Unit Of Use</value>
        [DataMember(Name="ExternalDeviceDesignator", EmitDefaultValue=false)]
        public string ExternalDeviceDesignator { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DeviceIdentifier {\n");
            sb.Append("  ExternalDeviceId: ").Append(ExternalDeviceId).Append("\n");
            sb.Append("  ExternalDeviceType: ").Append(ExternalDeviceType).Append("\n");
            sb.Append("  ExternalDeviceAgency: ").Append(ExternalDeviceAgency).Append("\n");
            sb.Append("  ExternalDeviceDesignator: ").Append(ExternalDeviceDesignator).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as DeviceIdentifier);
        }

        /// <summary>
        /// Returns true if DeviceIdentifier instances are equal
        /// </summary>
        /// <param name="other">Instance of DeviceIdentifier to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DeviceIdentifier other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ExternalDeviceId == other.ExternalDeviceId ||
                    this.ExternalDeviceId != null &&
                    this.ExternalDeviceId.Equals(other.ExternalDeviceId)
                ) && 
                (
                    this.ExternalDeviceType == other.ExternalDeviceType ||
                    this.ExternalDeviceType != null &&
                    this.ExternalDeviceType.Equals(other.ExternalDeviceType)
                ) && 
                (
                    this.ExternalDeviceAgency == other.ExternalDeviceAgency ||
                    this.ExternalDeviceAgency != null &&
                    this.ExternalDeviceAgency.Equals(other.ExternalDeviceAgency)
                ) && 
                (
                    this.ExternalDeviceDesignator == other.ExternalDeviceDesignator ||
                    this.ExternalDeviceDesignator != null &&
                    this.ExternalDeviceDesignator.Equals(other.ExternalDeviceDesignator)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ExternalDeviceId != null)
                    hash = hash * 59 + this.ExternalDeviceId.GetHashCode();
                if (this.ExternalDeviceType != null)
                    hash = hash * 59 + this.ExternalDeviceType.GetHashCode();
                if (this.ExternalDeviceAgency != null)
                    hash = hash * 59 + this.ExternalDeviceAgency.GetHashCode();
                if (this.ExternalDeviceDesignator != null)
                    hash = hash * 59 + this.ExternalDeviceDesignator.GetHashCode();
                return hash;
            }
        }
    }

}
