/* 
 * FDB Prizm Services
 *
 * Web API for accessing medical device information
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace DeviceSample.Model
{
    /// <summary>
    /// FDAProductCodeInfo
    /// </summary>
    [DataContract]
    public partial class FDAProductCodeInfo :  IEquatable<FDAProductCodeInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FDAProductCodeInfo" /> class.
        /// </summary>
        /// <param name="FDAProductCode">FDAProductCode.</param>
        /// <param name="FDAProductCodeName">FDAProductCodeName.</param>
        /// <param name="FDAProductClass">FDAProductClass.</param>
        public FDAProductCodeInfo(string FDAProductCode = default(string), string FDAProductCodeName = default(string), string FDAProductClass = default(string))
        {
            this.FDAProductCode = FDAProductCode;
            this.FDAProductCodeName = FDAProductCodeName;
            this.FDAProductClass = FDAProductClass;
        }
        
        /// <summary>
        /// Gets or Sets FDAProductCode
        /// </summary>
        [DataMember(Name="FDAProductCode", EmitDefaultValue=false)]
        public string FDAProductCode { get; set; }

        /// <summary>
        /// Gets or Sets FDAProductCodeName
        /// </summary>
        [DataMember(Name="FDAProductCodeName", EmitDefaultValue=false)]
        public string FDAProductCodeName { get; set; }

        /// <summary>
        /// Gets or Sets FDAProductClass
        /// </summary>
        [DataMember(Name="FDAProductClass", EmitDefaultValue=false)]
        public string FDAProductClass { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FDAProductCodeInfo {\n");
            sb.Append("  FDAProductCode: ").Append(FDAProductCode).Append("\n");
            sb.Append("  FDAProductCodeName: ").Append(FDAProductCodeName).Append("\n");
            sb.Append("  FDAProductClass: ").Append(FDAProductClass).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as FDAProductCodeInfo);
        }

        /// <summary>
        /// Returns true if FDAProductCodeInfo instances are equal
        /// </summary>
        /// <param name="other">Instance of FDAProductCodeInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FDAProductCodeInfo other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.FDAProductCode == other.FDAProductCode ||
                    this.FDAProductCode != null &&
                    this.FDAProductCode.Equals(other.FDAProductCode)
                ) && 
                (
                    this.FDAProductCodeName == other.FDAProductCodeName ||
                    this.FDAProductCodeName != null &&
                    this.FDAProductCodeName.Equals(other.FDAProductCodeName)
                ) && 
                (
                    this.FDAProductClass == other.FDAProductClass ||
                    this.FDAProductClass != null &&
                    this.FDAProductClass.Equals(other.FDAProductClass)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.FDAProductCode != null)
                    hash = hash * 59 + this.FDAProductCode.GetHashCode();
                if (this.FDAProductCodeName != null)
                    hash = hash * 59 + this.FDAProductCodeName.GetHashCode();
                if (this.FDAProductClass != null)
                    hash = hash * 59 + this.FDAProductClass.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
