/* 
 * FDB Device Services
 *
 * Web API for accessing medical device information
 *
 * OpenAPI spec version: 1.05
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace DeviceSearch.Model
{
    /// <summary>
    /// Returns the HCPCS information
    /// </summary>
    [DataContract]
    public partial class HCPCSInfo : IEquatable<HCPCSInfo>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HCPCSInfo" /> class.
        /// </summary>
        /// <param name="HCPCSCode">Returns the HCPCS code.</param>
        public HCPCSInfo(string HCPCSCode = default(string))
        {
            this.HCPCSCode = HCPCSCode;
        }

        /// <summary>
        /// Returns the HCPCS code
        /// </summary>
        /// <value>Returns the HCPCS code</value>
        [DataMember(Name = "HCPCSCode", EmitDefaultValue = false)]
        public string HCPCSCode { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HCPCSInfo {\n");
            sb.Append("  HCPCSCode: ").Append(HCPCSCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as HCPCSInfo);
        }

        /// <summary>
        /// Returns true if HCPCSInfo instances are equal
        /// </summary>
        /// <param name="other">Instance of HCPCSInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HCPCSInfo other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return
                (
                    this.HCPCSCode == other.HCPCSCode ||
                    this.HCPCSCode != null &&
                    this.HCPCSCode.Equals(other.HCPCSCode)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.HCPCSCode != null)
                    hash = hash * 59 + this.HCPCSCode.GetHashCode();
                return hash;
            }
        }

    }

}
