/*
 * FDB Device Services
 *
 * Web API for accessing medical device information
 *
 * OpenAPI spec version: 1.05
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Text;

namespace DeviceSample.Model
{
    /// <summary>
    /// LabelerContact
    /// </summary>
    [DataContract]
    public partial class LabelerContact : IEquatable<LabelerContact>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LabelerContact" /> class.
        /// </summary>
        /// <param name="LabelerEmail">LabelerEmail.</param>
        /// <param name="LabelerPhone">LabelerPhone.</param>
        /// <param name="LabelerPhoneExtension">LabelerPhoneExtension.</param>
        public LabelerContact(string LabelerEmail = default(string), string LabelerPhone = default(string), string LabelerPhoneExtension = default(string))
        {
            this.LabelerEmail = LabelerEmail;
            this.LabelerPhone = LabelerPhone;
            this.LabelerPhoneExtension = LabelerPhoneExtension;
        }

        /// <summary>
        /// Gets or Sets LabelerEmail
        /// </summary>
        [DataMember(Name = "LabelerEmail", EmitDefaultValue = false)]
        public string LabelerEmail { get; set; }

        /// <summary>
        /// Gets or Sets LabelerPhone
        /// </summary>
        [DataMember(Name = "LabelerPhone", EmitDefaultValue = false)]
        public string LabelerPhone { get; set; }

        /// <summary>
        /// Gets or Sets LabelerPhoneExtension
        /// </summary>
        [DataMember(Name = "LabelerPhoneExtension", EmitDefaultValue = false)]
        public string LabelerPhoneExtension { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LabelerContact {\n");
            sb.Append("  LabelerEmail: ").Append(LabelerEmail).Append("\n");
            sb.Append("  LabelerPhone: ").Append(LabelerPhone).Append("\n");
            sb.Append("  LabelerPhoneExtension: ").Append(LabelerPhoneExtension).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as LabelerContact);
        }

        /// <summary>
        /// Returns true if LabelerContact instances are equal
        /// </summary>
        /// <param name="other">Instance of LabelerContact to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LabelerContact other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return
                (
                    this.LabelerEmail == other.LabelerEmail ||
                    this.LabelerEmail != null &&
                    this.LabelerEmail.Equals(other.LabelerEmail)
                ) &&
                (
                    this.LabelerPhone == other.LabelerPhone ||
                    this.LabelerPhone != null &&
                    this.LabelerPhone.Equals(other.LabelerPhone)
                ) &&
                (
                    this.LabelerPhoneExtension == other.LabelerPhoneExtension ||
                    this.LabelerPhoneExtension != null &&
                    this.LabelerPhoneExtension.Equals(other.LabelerPhoneExtension)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.LabelerEmail != null)
                    hash = hash * 59 + this.LabelerEmail.GetHashCode();
                if (this.LabelerPhone != null)
                    hash = hash * 59 + this.LabelerPhone.GetHashCode();
                if (this.LabelerPhoneExtension != null)
                    hash = hash * 59 + this.LabelerPhoneExtension.GetHashCode();
                return hash;
            }
        }
    }
}