/* 
 * FDB Prizm Services
 *
 * Web API for accessing medical device information
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace DeviceSample.Model
{
    /// <summary>
    /// Package
    /// </summary>
    [DataContract]
    public partial class Package :  IEquatable<Package>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Package" /> class.
        /// </summary>
        /// <param name="PrizmPackageId">PrizmPackageId.</param>
        /// <param name="PackageCount">PackageCount.</param>
        /// <param name="TotalDeviceCount">TotalDeviceCount.</param>
        /// <param name="PackageTypeCode">PackageTypeCode.</param>
        /// <param name="PackageTypeDesc">PackageTypeDesc.</param>
        /// <param name="InnerPrizmPackageId">InnerPrizmPackageId.</param>
        /// <param name="PackageStatusId">PackageStatusId.</param>
        /// <param name="PackageStatusDesc">PackageStatusDesc.</param>
        /// <param name="IsUnitOfUse">IsUnitOfUse.</param>
        /// <param name="PackageIdentifiers">PackageIdentifiers.</param>
        /// <param name="PackagingCompanies">PackagingCompanies.</param>
        public Package(int? PrizmPackageId = default(int?), string PackageCount = default(string), string TotalDeviceCount = default(string), string PackageTypeCode = default(string), string PackageTypeDesc = default(string), int? InnerPrizmPackageId = default(int?), int? PackageStatusId = default(int?), string PackageStatusDesc = default(string), bool? IsUnitOfUse = default(bool?), List<PackageIdentifier> PackageIdentifiers = default(List<PackageIdentifier>), List<PackagingCompany> PackagingCompanies = default(List<PackagingCompany>))
        {
            this.PrizmPackageId = PrizmPackageId;
            this.PackageCount = PackageCount;
            this.TotalDeviceCount = TotalDeviceCount;
            this.PackageTypeCode = PackageTypeCode;
            this.PackageTypeDesc = PackageTypeDesc;
            this.InnerPrizmPackageId = InnerPrizmPackageId;
            this.PackageStatusId = PackageStatusId;
            this.PackageStatusDesc = PackageStatusDesc;
            this.IsUnitOfUse = IsUnitOfUse;
            this.PackageIdentifiers = PackageIdentifiers;
            this.PackagingCompanies = PackagingCompanies;
        }
        
        /// <summary>
        /// Gets or Sets PrizmPackageId
        /// </summary>
        [DataMember(Name="PrizmPackageId", EmitDefaultValue=false)]
        public int? PrizmPackageId { get; set; }

        /// <summary>
        /// Gets or Sets PackageCount
        /// </summary>
        [DataMember(Name="PackageCount", EmitDefaultValue=false)]
        public string PackageCount { get; set; }

        /// <summary>
        /// Gets or Sets TotalDeviceCount
        /// </summary>
        [DataMember(Name="TotalDeviceCount", EmitDefaultValue=false)]
        public string TotalDeviceCount { get; set; }

        /// <summary>
        /// Gets or Sets PackageTypeCode
        /// </summary>
        [DataMember(Name="PackageTypeCode", EmitDefaultValue=false)]
        public string PackageTypeCode { get; set; }

        /// <summary>
        /// Gets or Sets PackageTypeDesc
        /// </summary>
        [DataMember(Name="PackageTypeDesc", EmitDefaultValue=false)]
        public string PackageTypeDesc { get; set; }

        /// <summary>
        /// Gets or Sets InnerPrizmPackageId
        /// </summary>
        [DataMember(Name="InnerPrizmPackageId", EmitDefaultValue=false)]
        public int? InnerPrizmPackageId { get; set; }

        /// <summary>
        /// Gets or Sets PackageStatusId
        /// </summary>
        [DataMember(Name="PackageStatusId", EmitDefaultValue=false)]
        public int? PackageStatusId { get; set; }

        /// <summary>
        /// Gets or Sets PackageStatusDesc
        /// </summary>
        [DataMember(Name="PackageStatusDesc", EmitDefaultValue=false)]
        public string PackageStatusDesc { get; set; }

        /// <summary>
        /// Gets or Sets IsUnitOfUse
        /// </summary>
        [DataMember(Name="IsUnitOfUse", EmitDefaultValue=false)]
        public bool? IsUnitOfUse { get; set; }

        /// <summary>
        /// Gets or Sets PackageIdentifiers
        /// </summary>
        [DataMember(Name="PackageIdentifiers", EmitDefaultValue=false)]
        public List<PackageIdentifier> PackageIdentifiers { get; set; }

        /// <summary>
        /// Gets or Sets PackagingCompanies
        /// </summary>
        [DataMember(Name="PackagingCompanies", EmitDefaultValue=false)]
        public List<PackagingCompany> PackagingCompanies { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Package {\n");
            sb.Append("  PrizmPackageId: ").Append(PrizmPackageId).Append("\n");
            sb.Append("  PackageCount: ").Append(PackageCount).Append("\n");
            sb.Append("  TotalDeviceCount: ").Append(TotalDeviceCount).Append("\n");
            sb.Append("  PackageTypeCode: ").Append(PackageTypeCode).Append("\n");
            sb.Append("  PackageTypeDesc: ").Append(PackageTypeDesc).Append("\n");
            sb.Append("  InnerPrizmPackageId: ").Append(InnerPrizmPackageId).Append("\n");
            sb.Append("  PackageStatusId: ").Append(PackageStatusId).Append("\n");
            sb.Append("  PackageStatusDesc: ").Append(PackageStatusDesc).Append("\n");
            sb.Append("  IsUnitOfUse: ").Append(IsUnitOfUse).Append("\n");
            sb.Append("  PackageIdentifiers: ").Append(PackageIdentifiers).Append("\n");
            sb.Append("  PackagingCompanies: ").Append(PackagingCompanies).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Package);
        }

        /// <summary>
        /// Returns true if Package instances are equal
        /// </summary>
        /// <param name="other">Instance of Package to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Package other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.PrizmPackageId == other.PrizmPackageId ||
                    this.PrizmPackageId != null &&
                    this.PrizmPackageId.Equals(other.PrizmPackageId)
                ) && 
                (
                    this.PackageCount == other.PackageCount ||
                    this.PackageCount != null &&
                    this.PackageCount.Equals(other.PackageCount)
                ) && 
                (
                    this.TotalDeviceCount == other.TotalDeviceCount ||
                    this.TotalDeviceCount != null &&
                    this.TotalDeviceCount.Equals(other.TotalDeviceCount)
                ) && 
                (
                    this.PackageTypeCode == other.PackageTypeCode ||
                    this.PackageTypeCode != null &&
                    this.PackageTypeCode.Equals(other.PackageTypeCode)
                ) && 
                (
                    this.PackageTypeDesc == other.PackageTypeDesc ||
                    this.PackageTypeDesc != null &&
                    this.PackageTypeDesc.Equals(other.PackageTypeDesc)
                ) && 
                (
                    this.InnerPrizmPackageId == other.InnerPrizmPackageId ||
                    this.InnerPrizmPackageId != null &&
                    this.InnerPrizmPackageId.Equals(other.InnerPrizmPackageId)
                ) && 
                (
                    this.PackageStatusId == other.PackageStatusId ||
                    this.PackageStatusId != null &&
                    this.PackageStatusId.Equals(other.PackageStatusId)
                ) && 
                (
                    this.PackageStatusDesc == other.PackageStatusDesc ||
                    this.PackageStatusDesc != null &&
                    this.PackageStatusDesc.Equals(other.PackageStatusDesc)
                ) && 
                (
                    this.IsUnitOfUse == other.IsUnitOfUse ||
                    this.IsUnitOfUse != null &&
                    this.IsUnitOfUse.Equals(other.IsUnitOfUse)
                ) && 
                (
                    this.PackageIdentifiers == other.PackageIdentifiers ||
                    this.PackageIdentifiers != null &&
                    this.PackageIdentifiers.SequenceEqual(other.PackageIdentifiers)
                ) && 
                (
                    this.PackagingCompanies == other.PackagingCompanies ||
                    this.PackagingCompanies != null &&
                    this.PackagingCompanies.SequenceEqual(other.PackagingCompanies)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.PrizmPackageId != null)
                    hash = hash * 59 + this.PrizmPackageId.GetHashCode();
                if (this.PackageCount != null)
                    hash = hash * 59 + this.PackageCount.GetHashCode();
                if (this.TotalDeviceCount != null)
                    hash = hash * 59 + this.TotalDeviceCount.GetHashCode();
                if (this.PackageTypeCode != null)
                    hash = hash * 59 + this.PackageTypeCode.GetHashCode();
                if (this.PackageTypeDesc != null)
                    hash = hash * 59 + this.PackageTypeDesc.GetHashCode();
                if (this.InnerPrizmPackageId != null)
                    hash = hash * 59 + this.InnerPrizmPackageId.GetHashCode();
                if (this.PackageStatusId != null)
                    hash = hash * 59 + this.PackageStatusId.GetHashCode();
                if (this.PackageStatusDesc != null)
                    hash = hash * 59 + this.PackageStatusDesc.GetHashCode();
                if (this.IsUnitOfUse != null)
                    hash = hash * 59 + this.IsUnitOfUse.GetHashCode();
                if (this.PackageIdentifiers != null)
                    hash = hash * 59 + this.PackageIdentifiers.GetHashCode();
                if (this.PackagingCompanies != null)
                    hash = hash * 59 + this.PackagingCompanies.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
