/* 
 * FDB Prizm Services
 *
 * Web API for accessing medical device information
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace DeviceSample.Model
{
    /// <summary>
    /// PackageIdentifier
    /// </summary>
    [DataContract]
    public partial class PackageIdentifier :  IEquatable<PackageIdentifier>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PackageIdentifier" /> class.
        /// </summary>
        /// <param name="ExternalPackageId">ExternalPackageId.</param>
        /// <param name="ExternalPackageIdType">ExternalPackageIdType.</param>
        /// <param name="ExternalPackageIdDesignatorAgency">ExternalPackageIdDesignatorAgency.</param>
        /// <param name="ExternalPackageIdDesignator">ExternalPackageIdDesignator.</param>
        public PackageIdentifier(string ExternalPackageId = default(string), string ExternalPackageIdType = default(string), string ExternalPackageIdDesignatorAgency = default(string), string ExternalPackageIdDesignator = default(string))
        {
            this.ExternalPackageId = ExternalPackageId;
            this.ExternalPackageIdType = ExternalPackageIdType;
            this.ExternalPackageIdDesignatorAgency = ExternalPackageIdDesignatorAgency;
            this.ExternalPackageIdDesignator = ExternalPackageIdDesignator;
        }
        
        /// <summary>
        /// Gets or Sets ExternalPackageId
        /// </summary>
        [DataMember(Name="ExternalPackageId", EmitDefaultValue=false)]
        public string ExternalPackageId { get; set; }

        /// <summary>
        /// Gets or Sets ExternalPackageIdType
        /// </summary>
        [DataMember(Name="ExternalPackageIdType", EmitDefaultValue=false)]
        public string ExternalPackageIdType { get; set; }

        /// <summary>
        /// Gets or Sets ExternalPackageIdDesignatorAgency
        /// </summary>
        [DataMember(Name="ExternalPackageIdDesignatorAgency", EmitDefaultValue=false)]
        public string ExternalPackageIdDesignatorAgency { get; set; }

        /// <summary>
        /// Gets or Sets ExternalPackageIdDesignator
        /// </summary>
        [DataMember(Name="ExternalPackageIdDesignator", EmitDefaultValue=false)]
        public string ExternalPackageIdDesignator { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PackageIdentifier {\n");
            sb.Append("  ExternalPackageId: ").Append(ExternalPackageId).Append("\n");
            sb.Append("  ExternalPackageIdType: ").Append(ExternalPackageIdType).Append("\n");
            sb.Append("  ExternalPackageIdDesignatorAgency: ").Append(ExternalPackageIdDesignatorAgency).Append("\n");
            sb.Append("  ExternalPackageIdDesignator: ").Append(ExternalPackageIdDesignator).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PackageIdentifier);
        }

        /// <summary>
        /// Returns true if PackageIdentifier instances are equal
        /// </summary>
        /// <param name="other">Instance of PackageIdentifier to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PackageIdentifier other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ExternalPackageId == other.ExternalPackageId ||
                    this.ExternalPackageId != null &&
                    this.ExternalPackageId.Equals(other.ExternalPackageId)
                ) && 
                (
                    this.ExternalPackageIdType == other.ExternalPackageIdType ||
                    this.ExternalPackageIdType != null &&
                    this.ExternalPackageIdType.Equals(other.ExternalPackageIdType)
                ) && 
                (
                    this.ExternalPackageIdDesignatorAgency == other.ExternalPackageIdDesignatorAgency ||
                    this.ExternalPackageIdDesignatorAgency != null &&
                    this.ExternalPackageIdDesignatorAgency.Equals(other.ExternalPackageIdDesignatorAgency)
                ) && 
                (
                    this.ExternalPackageIdDesignator == other.ExternalPackageIdDesignator ||
                    this.ExternalPackageIdDesignator != null &&
                    this.ExternalPackageIdDesignator.Equals(other.ExternalPackageIdDesignator)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ExternalPackageId != null)
                    hash = hash * 59 + this.ExternalPackageId.GetHashCode();
                if (this.ExternalPackageIdType != null)
                    hash = hash * 59 + this.ExternalPackageIdType.GetHashCode();
                if (this.ExternalPackageIdDesignatorAgency != null)
                    hash = hash * 59 + this.ExternalPackageIdDesignatorAgency.GetHashCode();
                if (this.ExternalPackageIdDesignator != null)
                    hash = hash * 59 + this.ExternalPackageIdDesignator.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
