/* 
 * FDB Device Services
 *
 * Web API for accessing medical device information
 *
 * OpenAPI spec version: 1.01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace DeviceSample.Model
{
    /// <summary>
    /// SearchDevicesResponse
    /// </summary>
    [DataContract]
    public partial class SearchDevicesResponse :  IEquatable<SearchDevicesResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchDevicesResponse" /> class.
        /// </summary>
        /// <param name="SeviceCallId">Returns the unique identifier for each service call..</param>
        /// <param name="Limit">Returns the maximum number of results that are returned.</param>
        /// <param name="Offset">Returns the index page number of the data that is returned.</param>
        /// <param name="TotalResultCount">Returns the total number of available results.</param>
        /// <param name="Items">Items.</param>
        public SearchDevicesResponse(string SeviceCallId = null, int? Limit = null, int? Offset = null, int? TotalResultCount = null, List<Device> Items = null)
        {
            this.SeviceCallId = SeviceCallId;
            this.Limit = Limit;
            this.Offset = Offset;
            this.TotalResultCount = TotalResultCount;
            this.Items = Items;
        }
        
        /// <summary>
        /// Returns the unique identifier for each service call.
        /// </summary>
        /// <value>Returns the unique identifier for each service call.</value>
        [DataMember(Name="SeviceCallId", EmitDefaultValue=false)]
        public string SeviceCallId { get; set; }
        /// <summary>
        /// Returns the maximum number of results that are returned
        /// </summary>
        /// <value>Returns the maximum number of results that are returned</value>
        [DataMember(Name="Limit", EmitDefaultValue=false)]
        public int? Limit { get; set; }
        /// <summary>
        /// Returns the index page number of the data that is returned
        /// </summary>
        /// <value>Returns the index page number of the data that is returned</value>
        [DataMember(Name="Offset", EmitDefaultValue=false)]
        public int? Offset { get; set; }
        /// <summary>
        /// Returns the total number of available results
        /// </summary>
        /// <value>Returns the total number of available results</value>
        [DataMember(Name="TotalResultCount", EmitDefaultValue=false)]
        public int? TotalResultCount { get; set; }
        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [DataMember(Name="Items", EmitDefaultValue=false)]
        public List<Device> Items { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SearchDevicesResponse {\n");
            sb.Append("  SeviceCallId: ").Append(SeviceCallId).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Offset: ").Append(Offset).Append("\n");
            sb.Append("  TotalResultCount: ").Append(TotalResultCount).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as SearchDevicesResponse);
        }

        /// <summary>
        /// Returns true if SearchDevicesResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of SearchDevicesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SearchDevicesResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.SeviceCallId == other.SeviceCallId ||
                    this.SeviceCallId != null &&
                    this.SeviceCallId.Equals(other.SeviceCallId)
                ) && 
                (
                    this.Limit == other.Limit ||
                    this.Limit != null &&
                    this.Limit.Equals(other.Limit)
                ) && 
                (
                    this.Offset == other.Offset ||
                    this.Offset != null &&
                    this.Offset.Equals(other.Offset)
                ) && 
                (
                    this.TotalResultCount == other.TotalResultCount ||
                    this.TotalResultCount != null &&
                    this.TotalResultCount.Equals(other.TotalResultCount)
                ) && 
                (
                    this.Items == other.Items ||
                    this.Items != null &&
                    this.Items.SequenceEqual(other.Items)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.SeviceCallId != null)
                    hash = hash * 59 + this.SeviceCallId.GetHashCode();
                if (this.Limit != null)
                    hash = hash * 59 + this.Limit.GetHashCode();
                if (this.Offset != null)
                    hash = hash * 59 + this.Offset.GetHashCode();
                if (this.TotalResultCount != null)
                    hash = hash * 59 + this.TotalResultCount.GetHashCode();
                if (this.Items != null)
                    hash = hash * 59 + this.Items.GetHashCode();
                return hash;
            }
        }
    }

}
