/* 
 * FDB Prizm Services
 *
 * Web API for accessing medical device information
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace DeviceSample.Model
{
    /// <summary>
    /// Size
    /// </summary>
    [DataContract]
    public partial class Size :  IEquatable<Size>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Size" /> class.
        /// </summary>
        /// <param name="SizeUnitAbbreviation">SizeUnitAbbreviation.</param>
        /// <param name="SizeValue">SizeValue.</param>
        /// <param name="SizeType">SizeType.</param>
        public Size(string SizeUnitAbbreviation = default(string), string SizeValue = default(string), string SizeType = default(string))
        {
            this.SizeUnitAbbreviation = SizeUnitAbbreviation;
            this.SizeValue = SizeValue;
            this.SizeType = SizeType;
        }
        
        /// <summary>
        /// Gets or Sets SizeUnitAbbreviation
        /// </summary>
        [DataMember(Name="SizeUnitAbbreviation", EmitDefaultValue=false)]
        public string SizeUnitAbbreviation { get; set; }

        /// <summary>
        /// Gets or Sets SizeValue
        /// </summary>
        [DataMember(Name="SizeValue", EmitDefaultValue=false)]
        public string SizeValue { get; set; }

        /// <summary>
        /// Gets or Sets SizeType
        /// </summary>
        [DataMember(Name="SizeType", EmitDefaultValue=false)]
        public string SizeType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Size {\n");
            sb.Append("  SizeUnitAbbreviation: ").Append(SizeUnitAbbreviation).Append("\n");
            sb.Append("  SizeValue: ").Append(SizeValue).Append("\n");
            sb.Append("  SizeType: ").Append(SizeType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Size);
        }

        /// <summary>
        /// Returns true if Size instances are equal
        /// </summary>
        /// <param name="other">Instance of Size to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Size other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.SizeUnitAbbreviation == other.SizeUnitAbbreviation ||
                    this.SizeUnitAbbreviation != null &&
                    this.SizeUnitAbbreviation.Equals(other.SizeUnitAbbreviation)
                ) && 
                (
                    this.SizeValue == other.SizeValue ||
                    this.SizeValue != null &&
                    this.SizeValue.Equals(other.SizeValue)
                ) && 
                (
                    this.SizeType == other.SizeType ||
                    this.SizeType != null &&
                    this.SizeType.Equals(other.SizeType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.SizeUnitAbbreviation != null)
                    hash = hash * 59 + this.SizeUnitAbbreviation.GetHashCode();
                if (this.SizeValue != null)
                    hash = hash * 59 + this.SizeValue.GetHashCode();
                if (this.SizeType != null)
                    hash = hash * 59 + this.SizeType.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
